### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by Mwiti** [GabrielAlva/SwiftPages#1]
Hi there! Great control here... one question (kind of a noob so please bare with me :) ).... 

I want to get rid of the navigation bar because its just sitted there... blank... and its eating up space... Thanks in advance :)

**Comment by GabrielAlva** [comment]
Hi!
Thanks, I gotta say Im not too sure which bar you are referring too, but you can set the color property of any item to be UIColor.clearColor(). That should do the job!

So if for example you refer to the animated bar that scrolls below the items on the main bar, you can do:

``` swift
yourSwiftPagesInstance.setAnimatedBarColor(UIColor.clearColor())
```

**Comment by Mwiti** [comment]
The white bar at the very top (Navigation Bar). That's the one I want to get rid of. 

![screen shot 2015-07-24 at 11 20 26 pm](https://cloud.githubusercontent.com/assets/4980424/8883889/f37dc7c6-325a-11e5-89e5-4ddef326f4b7.png)

**Comment by Mwiti** [comment]
The white bar. That's the one I want to get rid of. (Check attachment)

On Friday, July 24, 2015, Gabriel Alvarado <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> Hi!
> Thanks, I gotta say Im not too sure which bar you are referring too, but
> you can set the color property of any item to be UIColor.clearColor(). That
> should do the job :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GabrielAlva/SwiftPages/issues/1#issuecomment-124705475
> .

## 

Mwiti.

**Comment by GabrielAlva** [comment]
you can do it by setting the frame of the SwiftPages view to have the origin you would like. So if the view is created programmatically:

``` swift
//Instantiation and the setting of the size and position
        let swiftPagesView : SwiftPages!
        swiftPagesView = SwiftPages(frame: CGRectMake(0, 0, self.view.frame.width, self.view.frame.height))
```

If your VC has a navigation bar then the origin (0,0) will show the bar as in the screenshot.

**Comment by Mwiti** [comment]
i used the interface builder route... is there a way to do it or i have to create it in code?

**Comment by GabrielAlva** [comment]
no its perfectly ok to use the interface builder. Just set your constraints of the view to the ones your would like.

**Comment by Mwiti** [comment]
Thats how my view is set up in interface builder... it should cover the whole screen, no? (I've applieed the "reset to suggested constraints" option in the pin menu for the View...
When i run it, It still shows up with the nav bar... 😳

![screen shot 2015-07-25 at 12 01 04 am](https://cloud.githubusercontent.com/assets/4980424/8884577/6ebe302e-3260-11e5-93ec-9a1aec6f8b79.png)

**Comment by GabrielAlva** [comment]
On the storyboard, the constraints for the top need to specify that it will be align with the top layout guide which always gives a constant of -20. Please add that constraint, then it should work.

**Comment by Mwiti** [comment]
Got it! Thanks a ton! :)

**Comment by GabrielAlva** [comment]
Hi, If you would like me to pass you a test project I made, you can email me (its in my profile) and I'll send it!

**Comment by Mwiti** [comment]
please send me the project. I'll really appreciate. Email : kennethmwiri@gmail.com. 

and another thing... If i want the 'topbar' at the bottom... what should i do... ? i've tried editing the origin values but nothing... 

Thanks. :-)

**Comment by GabrielAlva** [comment]
For the Bottom bar, use the `setDistanceToBottom` API to set the bottom distance to the bar.

**Comment by Mwiti** [comment]
if i set the distanceToBottom to 200 for example, this is what i get.... I want the bar with the icons to be at the bottom of the viewController but i cant call the distanceToBottom method on the topBar... Here i have called the method on the swiftPagesView (seems to be the only way i can call it)... 

![screen shot 2015-07-27 at 11 35 40 pm](https://cloud.githubusercontent.com/assets/4980424/8917026/44eda252-34b8-11e5-8489-8eaab3e19376.png)

**Comment by GabrielAlva** [comment]
I see what you mean now, for that you would need to modify the class itself and set the frame of the bar (var topBar) to the position you would like. The frame is set on line 86, below the `//Set the top bar` comment.

**Comment by Mwiti** [comment]
when i set it this way -      

 topBar = UIView(frame: CGRectMake(0, 603, containerView.frame.size.width, topBarHeight))

it works very well in the iphone 6 simulator but in the others its out of position as in the image... 

The result is the same if i use the following:

```
    topBar = UIView(frame: CGRectMake(0, containerView.frame.height, containerView.frame.size.width, topBarHeight))
```

![screen shot 2015-07-28 at 9 10 27 pm](https://cloud.githubusercontent.com/assets/4980424/8939517/906ee08c-356d-11e5-9fa1-ace763e58c70.png)
