### ISSUE TITLE
Space between ViewController

### ISSUE THREAD

**Issue by apm-lucas-zacharias** [GabrielAlva/SwiftPages#19]
Hi and first of all thanks for this project.

Is it possible to insert a padding between the VC like here: http://stackoverflow.com/questions/20694679/horizontal-padding-between-uipageviewcontroller-child-view-controllers

**Comment by GabrielAlva** [comment]
Hi,
Sorry for the delay, I was catching up on some issues with this library which I solved now. You could do it by modifying the width of the scrollview in the `SwiftPages` class and setting the x origin of each view added to it accordingly to the space you wish to have.
