### ISSUE TITLE
Positioning off for swiftpages scrollview when parent VC is embeded in a navigation controller

### ISSUE THREAD

**Issue by mikejonas** [GabrielAlva/SwiftPages#2]
This bug causes the scrollview positioning to be off and enables it to be scrolled in any direction

To recreate:
- From the demo project storyboard, embed 'First ExampleVC' in a navigation controller
- move the storyboard entry point to the new navigation controller and run project

**Comment by mikejonas** [comment]
I found out that this was an issue with how apple lays out UIScrollView's, not with the plugin.  I fixed it by setting [self.automaticallyAdjustsScrollViewInsets = false](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIViewController_Class/index.html#//apple_ref/occ/instp/UIViewController/automaticallyAdjustsScrollViewInsets) in the viewController where SwiftPages is being used.

**Comment by GabrielAlva** [comment]
Thanks for the feedback Mike, good to know about this implementation detail.
