### ISSUE TITLE
App crashed when the first orientation change is to rotate to "Upside Down"

### ISSUE THREAD

**Issue by wjiuxing** [GabrielAlva/SwiftPages#26]
**Reproduce Steps**:
0. Rotate your simulator to Landscape Left(or Right);
1. Run you swift demo project;
2. Select any of entry in the first page to swift demo view controller;
3. Rotate you simulator to Upside Down.

**Expected**:
The app could stay as its orientation as other apps do.

**Result**:
The app crashed because it unwrapped an nil currentPage value.

**My Analysis**:
The two methods, _orientationWillChange_ and _orientationDidChange_, could not be called same times in this case. The _orientationWillChange_ method is called when status bar orientation will change because it observed the UIApplicationWillChangeStatusBarOrientationNotification. And the _orientationDidChange_ method is called when device orientation did change because of the UIDeviceOrientationDidChangeNotification. When the first orientation change is to rotate to Upside Down, the status bar orientation won’t be changed and the currentPage has an nil value but the device orientation did. So there will unwrap the nil value and crash the app. I think the easiest resolution is to set the default value 0 to the currentPage when declared.

Thanks.

**Comment by GabrielAlva** [comment]
I fixed it, it was due to an uninitialised currentPage var. I pushed the fix, thanks for catching it!

**Comment by wjiuxing** [comment]
Cheers. I will close the issue. :)
