### ISSUE TITLE
is there a way to customize if the navigation buttons are wider than the width of the phone

### ISSUE THREAD

**Issue by trestles** [GabrielAlva/SwiftPages#3]
I'm interested in this control (it looks really slick) but we will be generating our navigation buttons dynamically and could have up to 8 or 10 which would be wider than the phone. Could this component handle this? 

thx

**Comment by GabrielAlva** [comment]
Hi,
It would need to implement a UIScrollView on the bar instead of a view, that way (with the right settings on the scroll view) you can scroll through the buttons and and set specific behaviours for the scroller (e.g. center a button onscreen when touched).
