### ISSUE TITLE
Swift 2.2 selector syntax

### ISSUE THREAD

**Issue by WadeSellers** [GabrielAlva/SwiftPages#30]
I've forked your app and made the modification to the addTarget(selector...) that Swift2.2 recommends now. We are using their new #selector() method style in this latest version.

My update is attached to P.R. 31 for your consideration. Thank you Gabriel.

**Comment by GabrielAlva** [comment]
Hi, yeah I just got the PR. Thanks for contributing!

**Comment by WadeSellers** [comment]
Happy to help!
