### ISSUE TITLE
Wrong behavior when you rotate the device

### ISSUE THREAD

**Issue by pjcau** [GabrielAlva/SwiftPages#7]
Hi, 
your project is very interesting. I tested very well you application on my devices and I found this issue. When you rotate the device, there is same wrong behavior, it  doesn't hear that it changed the orientation.
I attached some images to undestand better the issue.

Thank you
<img width="372" alt="schermata 2015-08-08 alle 10 09 34" src="https://cloud.githubusercontent.com/assets/1088176/9149696/0917f5fa-3db6-11e5-8e54-d9bbeae9af66.png">
<img width="667" alt="schermata 2015-08-08 alle 10 09 10" src="https://cloud.githubusercontent.com/assets/1088176/9149697/17fb5ee0-3db6-11e5-9a80-b75d88bafc80.png">

**Comment by GabrielAlva** [comment]
Hi,
I fixed it to support all orientations now. It needs to be instantiated from a storyboard view from now on.
